import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextJS Blogs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  suppressHydrationWarning={true}>
      <body  className={`${inter.className} bg-teal-50 `}>
        <Navbar/>
       
        {children}</body>
    </html>
  )
}
